import { DifficultyLevel } from 'interfaces'

const DifficultyLevelList: DifficultyLevel[] = [
  {
    level: 1,
    key: 'easy',
    staticTiles: 38,
    tilesPerSquare: [5, 5, 4, 4, 4, 4, 4, 4, 4],
    text: 'easy',
    color: '#4caf50',
    desc: 'Great for casual play and beginners',
    isHintingEnabled: true,
  },
  {
    level: 2,
    key: 'medium',
    staticTiles: 32,
    tilesPerSquare: [5, 4, 4, 4, 3, 3, 3, 3, 3],
    text: 'medium',
    color: '#2196f3',
    desc: 'Balanced classic challenge',
    isHintingEnabled: true,
    isDefault: true,
  },
  {
    level: 3,
    key: 'hard',
    staticTiles: 28,
    tilesPerSquare: [4, 3, 3, 3, 3, 3, 3, 3, 3],
    text: 'hard',
    color: '#ff9800',
    desc: 'Advanced logic deduction',
    isHintingEnabled: true,
  },
  {
    level: 4,
    key: 'expert',
    staticTiles: 22,
    tilesPerSquare: [3, 3, 3, 3, 2, 2, 2, 2, 2],
    text: 'expert',
    color: '#e91e63',
    desc: 'No hints • High difficulty',
  },
  {
    level: 5,
    key: 'master',
    staticTiles: 16,
    tilesPerSquare: [2, 2, 2, 2, 2, 2, 2, 1, 1],
    text: 'master',
    color: '#9c27b0',
    desc: 'No hints • Minimal clues masterclass',
  },
  {
    level: 6,
    key: 'test',
    staticTiles: 80,
    tilesPerSquare: [8, 9, 9, 9, 9, 9, 9, 9, 9],
    text: 'one shot',
    color: '#ffb300',
    desc: '1 cell to solve • Instant speedrun',
    isHintingEnabled: true,
  },
]
export default DifficultyLevelList
